export const HOME = 'Home';
export const INVOICING = 'Invoicing';
export const STATS = 'Stats';
export const MESSAGES = 'Messages';
export const PROFILE = 'Profile';
export const MENTOR_SIGN_UP = 'MentorSignUp';
export const PATIENT_SIGN_UP = 'PatientSignUp';
export const LOGIN = 'Login';
export const ASK_CLIENT = '"AskClient"';
export const AV_CHAT_SCREEN="AVChatScreen"