export const HOME = 'Home';
export const INVOICING = 'Invoicing';
export const STATS = 'Stats';
export const CHATS_SCREENS = 'ChatScreens';
export const MESSAGES_TAB_ROUTE = 'MessageTabRoute';
export const PROFILE = 'Profile';
export const PROFILE_TAB_ROUTE = 'ProfileTabRoute';
export const MENTOR_SIGN_UP = 'MentorSignUp';
export const PATIENT_SIGN_UP = 'PatientSignUp';
export const LOGIN = 'Login';
export const ASK_CLIENT = '"AskClient"';
export const AV_CHAT_SCREEN="AVChatScreen"
export const CHATS_SCREEN="Chats"
export const CHATS_SCREEN_TWILLIO="ChatsTwillio"
export const CHATS_ROOM_SCREEN_TWILLIO="ChatsRoomTwillio"
export const CREATE_CHAT_SCREEN_TWILLIO="CreateChatsRoomTwillio"