export const PATIENT = 'Patient';
export const MENTOR = 'Mentor';
export const HOME = 'Home';
export const HOME_TAB_ROUTE = 'HomeTabRoute';
export const INVOICING = 'Invoicing';
export const STATS = 'Stats';
export const MESSAGES = 'Messages';
export const PROFILE = 'Profile';
export const ALL = 'All';
export const APPOINMENTS = 'Appoinments';
export const ARTICLES = 'Articles';
export const SAVED = 'Saved';
export const MENTORS_LIST = 'MentorsList';
export const HELLO = 'Hello';
export const HARDWARE_SUPPORT="Hardware to support video calls is not available"
export const ERROR="Error"
export const PERMISSIONS_ACCESS="Permission to access hardware was blocked, please grant manually"
export const ONE_GRANTED="'One of the permissions was not granted'"
export const PERMISSIONS_GRANTED='Permission not granted'
export const YOU_JOINED_CALL="You'll be joined to this video call"
export const ARE_YOU_JOIN="Are you sure you want to join?"
export const YES="Yes"
export const NO="No"
export const RELOAD="Reload"
export const NO_DATA_FOUND="No data found"
export const ARE_YOU_LOGOUT="Are you sure want to log out?"
export const LOGOUT="Log Out"
export const NO_CANCEL='No, Cancel'
export const I_AM_SPECIALIST="I'm a specialist in"
export const I_WANT='I want to address'
export const ACCOUNT_DETAILS="Account Details"
export const PAYMENT="Payment"
export const LINK_EXPIRED="Meeting Link Expired"
export const PATIENT_EMAIL_ID="patientEmailId"
export const MENTOR_EMAIL_ID="mentorEmailId"